### ISSUE TITLE
details panel in metaproject gui fails to show all operations

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege-ontology-client#16]
When clicking on some roles, the operations fail to show up, issue seems to be in the details panel

**Comment by rsgoncalves** [comment]
I can't replicate. Do you not get the scrollbar on the operations field as in the screenshot below?

![screen shot 2016-07-21 at 12 31 24](https://cloud.githubusercontent.com/assets/4361140/17036008/3208f3b0-4f3f-11e6-9f35-5e36411bab5d.png)

**Comment by bdionne** [comment]
This looks to be a resizing issue. If the description is too long it doesn't wrap and the scrollbar gets lost. I use a MBA and usually have the app sized at about 60% of available real estate

**Comment by rsgoncalves** [comment]
Ok, I replicated the problem, working on a fix.
