### ISSUE TITLE
prompt diff fails to refresh state

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege-ontology-client#18]
if new server commits occur during an editing session, they show up in the commits list for the author in prompt. However if you select the commit no details appear in the changes panel. Seems like a refresh issue

**Comment by rsgoncalves** [comment]
Currently the client has no way of knowing that a commit occurred and that the view(s) should be updated.

**Comment by bdionne** [comment]
great, this works now. I'll need to add the fireEvent logic to `EditTab` also when it does a save, but I tested from the classes tab and that works ok.

I think we'll push this event firing down into the client where the commit occurs, less code

**Comment by rsgoncalves** [comment]
Glad that it works. I forgot to mention this issue in the closing commit, but this should be fixed now.
