### ISSUE TITLE
Logout error

### ISSUE THREAD

**Issue by johardi** [protegeproject/protege-ontology-client#20]
Selecting "Server > Logout" throws a logout error.

Looking at the console gives:

```
11:39:22.050 [AWT-EventQueue-0] WARN  o.p.e.owl.model.OWLModelManagerImpl -
Exception thrown by listener: org.protege.editor.owl.client.ClientSession$1.  Detatching bad listener.
```

**Comment by bdionne** [comment]
Maybe the same bug, when you logout and then login again as a different, the user name appears in the server menu and the ontology is opened but the server menu items (commit, show history,...) are all disabled

**Comment by bdionne** [comment]
Actually I think this is a non-issue. I was confusing connecting to the server with opening a project.

**Comment by bdionne** [comment]
There does seem to be a few issues with setting the [active ontology](https://gist.github.com/bdionne/95c661875b0805fd6430297b685afcb8) I noticed null pointers also form the active ontology tab.

**Comment by johardi** [comment]
Fix via https://github.com/protegeproject/protege-client/commit/e080c6fb4617917c2216225d8e6d54e9f73bd02a
