### ISSUE TITLE
UserToken needs expiration time

### ISSUE THREAD

**Issue by johardi** [protegeproject/protege-ontology-client#21]
The UserToken needs an expiration time so it won't live forever in the server.

There are 2 approaches to implement this feature:
1. The SessionManager will do a periodic scanning in its token table and will remove any expired token,
2. Each token has a "timer" that will auto-remove itself from the SessionManager.

**Comment by bdionne** [comment]
#2. looks simpler to me, and there's builtin collections in Java libs that support this kind of thing. 

It would be nice also to consolidate the `AuthToken` in metaproject with the [`HttpAuthResponse`](https://github.com/protegeproject/protege-server/blob/http-metaproject-integration/src/main/java/org/protege/editor/owl/server/http/messages/HttpAuthResponse.java)  object we send to the client. The only reason this was created was to create a unique id the client could use to build it's Authorization header for subsequent calls. The `AuthToken` already has such a field but it's private.

**Comment by johardi** [comment]
Closes via https://github.com/protegeproject/protege-server/commit/dc7d983fbc763b11888d7a1438cd3e050963f6c3
