### ISSUE TITLE
Weird commit behaviour in http-metaproject-integration branch

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege-ontology-client#23]
As root user I added a project, then opened that ontology project from the server, did a couple of changes, and in the end my commit consisted of the whole ontology + my changes. Is this intended?

**Comment by rsgoncalves** [comment]
When I login as another user and open the ontology project set up before, the same thing happens: I immediately have an uncommitted change set composed of the whole ontology.

**Comment by bdionne** [comment]
No, it's not the intended behavior. Sounds like you could be running with some stale code, are you sure you're not using the RMI branch?

If you provide some more detail (what plugins you have loaded, what ontology file you used, etc..) I can try to reproduce it.

**Comment by rsgoncalves** [comment]
Here's the list of artifacts I'm using (_repo:branch_)
- protege:5.0.1-history-search
- protege-client:http-metaproject-integration
- protege-server:http-metaproject-integration
- metaproject:master

In my plugins folder I have:
- metaproject-1.0.0-SNAPSHOT.jar
- protege-client-3.0.0-SNAPSHOT.jar
- protege-server-3.0.0-SNAPSHOT.jar

To replicate the issue:
- Log in as root and add project: [pizza ontology](http://protege.stanford.edu/ontologies/pizza/pizza.owl)
- In a separate editor, log in as guest
- Click `Server > Show uncommitted changes` and you'll see the whole ontology

**Comment by bdionne** [comment]
Interesting, yea I don't see it and I'm running almost the same code, with the exception of [metaproject](https://github.com/bdionne/metaproject/commit/b0373509e3c7), where I have a couple of workaround commits that seem unrelated.

I just tried your scenario and both clients show no uncommitted changes.

In addition to the history file you should see a snapshot file show up on the server, and on the client after you open the project. If you go to prompt diff the commits tab should be empty until you start making local changes.

**Comment by bdionne** [comment]
ok, I can reproduce this and I believe this [fixes](https://github.com/protegeproject/protege-client/commit/16d81b1bb4302d5d) it for now. 

After the snapshot and remote history are first loaded, the history needs to be reset. `EditTab` does this when it gets the ontology switched event from the `ClientSession`. This call probably needs to be in the client somewhere.

**Comment by rsgoncalves** [comment]
I see. With the new changes all works well so far.
