### ISSUE TITLE
Table of server ontologies shows duplicate entries in a seemingly non-deterministic manner

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege-ontology-client#26]
Sometimes `pizza` is the duplicate, other times `foo`.

![screen shot 2016-07-20 at 14 03 45](https://cloud.githubusercontent.com/assets/4361140/17003302/349d3d40-4e84-11e6-888b-839c66c5482f.png)

**Comment by bdionne** [comment]
pretty sure this is another manifestation of the metaproject [issue](https://github.com/protegeproject/metaproject/issues/1)
