### ISSUE TITLE
Missing commit from metaproject-integration branch

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege-ontology-client#35]
Commit 2345746 (metaproject-integration branch) should be git-cherry-picked into the http-metaproject-integration branch.

**Comment by bdionne** [comment]
hmm, I spent a few minutes looking at this, and each line seems to be accounted for in the http branch. Where specifically was the null pointer? Are you still seeing it?

**Comment by rsgoncalves** [comment]
I'm not getting the null pointer (it was in the uncommitted changes dialog). I just remembered that after starting working on the HTTP server I git cherry-picked the few last commits that didn't seem to be in the HTTP server commit log, but skipped this last one because it was conflicting at the time with some local changes of mine, and figured I'd post an issue before I forget again. I guess this can be closed then.

**Comment by bdionne** [comment]
ok, let's leave this around then until we're sure nothing was dropped. When I was merging/rebasing that branch a lot into the http branch there were often conflicts to fix. Normally when I'm not so lazy I make an effort to split commits into smaller chunks to preserve as much of the history and attribution as possible.

**Comment by bdionne** [comment]
this seems to be ok
