### ISSUE TITLE
Logout/Login of client causes exception

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege-ontology-client#38]
[Exceptions](https://gist.github.com/bdionne/d9946b2336d1337ba7407a5d786496bd) are thrown on logout, that are possibly related to [closing ontologies](https://github.com/protegeproject/protege-client/blob/http-metaproject-integration/src/main/java/org/protege/editor/owl/client/ClientSession.java#L132)

**Comment by johardi** [comment]
How did you produce the exception?

**Comment by bdionne** [comment]
I see it in different scenarios:

Login
Open a project
Logout

Sometimes after logout, when you login again and then open a project, it occurs then. 

I think this NoOp reasoner object has a `rootOntology` private variable that is becoming null

The metrics table model also throws the same exception if it's active when the logout occurs

**Comment by rsgoncalves** [comment]
I believe I managed to replicate this. Upon logout I got an empty error message dialog titled "Logout error". After pressing Ok on that dialog, I noticed that under `Server` both `Login` and `Logout` menu items were both enabled. Does this match with your experience Bob? Unfortunately I didn't get exceptions.

**Comment by johardi** [comment]
I have a definite scenario to reproduce the error and it seemed the exception didn't come from protege-client:

 1. Open any remote ontology from "File > Open from Protege OWL Server...". Make sure you have 'Ontology metrics' view open.
 2. Select "Server > Logout"
 3. It will then throw `Exception thrown by listener: org.protege.editor.owl.ui.view.AbstractActiveOntologyViewComponent$$Lambda$70/1197804101.  Detatching bad listener.`
 4. Followed by:
```
16:32:33.439 [AWT-EventQueue-0] ERROR o.p.editor.core.ProtegeApplication - Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
	at uk.ac.manchester.cs.owl.owlapi.OWLImmutableOntologyImpl.getImportsClosure(OWLImmutableOntologyImpl.java:842) ~[owlapi-osgidistribution-4.2.5.jar:4.2.5.20160517-0735]
	at uk.ac.manchester.cs.owl.owlapi.concurrent.ConcurrentOWLOntologyImpl.getImportsClosure(ConcurrentOWLOntologyImpl.java:190) ~[owlapi-osgidistribution-4.2.5.jar:4.2.5.20160517-0735]
	at org.semanticweb.owlapi.metrics.AbstractOWLMetric.getOntologies(AbstractOWLMetric.java:99) ~[owlapi-osgidistribution-4.2.5.jar:4.2.5.20160517-0735]
	at org.semanticweb.owlapi.metrics.ObjectCountMetric.getObjects(ObjectCountMetric.java:80) ~[owlapi-osgidistribution-4.2.5.jar:4.2.5.20160517-0735]
	at org.semanticweb.owlapi.metrics.ObjectCountMetric.recomputeMetric(ObjectCountMetric.java:69) ~[owlapi-osgidistribution-4.2.5.jar:4.2.5.20160517-0735]
	at org.semanticweb.owlapi.metrics.ObjectCountMetric.recomputeMetric(ObjectCountMetric.java:31) ~[owlapi-osgidistribution-4.2.5.jar:4.2.5.20160517-0735]
	at org.semanticweb.owlapi.metrics.AbstractOWLMetric.getValue(AbstractOWLMetric.java:82) ~[owlapi-osgidistribution-4.2.5.jar:4.2.5.20160517-0735]
	at org.semanticweb.owlapi.metrics.AbstractOWLMetric.getValue(AbstractOWLMetric.java:36) ~[owlapi-osgidistribution-4.2.5.jar:4.2.5.20160517-0735]
	at org.protege.editor.owl.ui.metrics.MetricsTableModel.getValueAt(MetricsTableModel.java:46) ~[classes/:na]
	at org.protege.editor.owl.ui.metrics.MetricsPanel$3.getTableCellRendererComponent(MetricsPanel.java:159) ~[classes/:na]
...
```
My observation is that the 'Ontology metrics' view failed to unregister the ontology when the logout action closed all active ontology in Protege.

**Comment by johardi** [comment]
For the exception produced by the 'Ontology metrics' table model, I think this is out of the scope of protege-client fixes. What's happened there is that the metrics failed to unregister the ontology when the logout action closed all remote ontologies in Protege.

**Comment by johardi** [comment]
Regarding the logout error related to ontology metrics, I think @matthewhorridge was right. There is something to do with OWLAPI.

All OWL metric objects require an OWL ontology during the initialization (see [here](https://github.com/owlcs/owlapi/blob/3e2d7fa990a74aeac82023fcab8987e548bfe7f5/tools/src/main/java/org/semanticweb/owlapi/metrics/AbstractOWLMetric.java#L47)). The metric can then use the setOntology() method to switch to different ontologies (see [here](https://github.com/owlcs/owlapi/blob/3e2d7fa990a74aeac82023fcab8987e548bfe7f5/tools/src/main/java/org/semanticweb/owlapi/metrics/AbstractOWLMetric.java#L58-L61)). But notice the switching requires the past ontology to perform cleaning the ontology listener. Now things will get bad when the user closes the past ontology (set to null reference) and the plugin code invokes the method, hence triggering the null pointer exception.

I think it should be safe to skip the remove-and-add the ontology change listener in the setOntology(), and just having the new reference and setDirty(true). What do you think @matthewhorridge?

```
public void setOntology(OWLOntology ontology) {
//        this.ontology.getOWLOntologyManager().removeOntologyChangeListener(this);
        this.ontology = ontology;
//        this.ontology.getOWLOntologyManager().addOntologyChangeListener(this);
        setDirty(true);
}
```

**Comment by bdionne** [comment]
I'm still seeing an exception [here](https://github.com/owlcs/owlapi/blob/version5/tools/src/main/java/org/semanticweb/owlapi/metrics/AbstractOWLMetric.java#L59). To reproduce, login and open a project, logout, then click to expose the active ontology panel.

It looks to me like the recent changes to `ClientSession` are doing the right thing, but the metrics code still has the closed ontology in one of its maps, however the owl manager field in that ontology is now null.

**Comment by bdionne** [comment]
[Here's](https://gist.github.com/bdionne/f2bf12929a46abce5867ccb61e978fc3) another instance of a null pointer, on logout/login, this time in a different place. 

The scenario was:
1. login on 8080 as root
2. change a class to add an annotation
3. go make coffee
4. come back and do a commit (token had timed out)
5. commit fails and forces a login
6. open project again and get the exception

**Comment by johardi** [comment]
Fixed via https://github.com/protegeproject/protege/commit/3de0fa6035c4f84c53fcb0ba7767a897df1cca53
