### ISSUE TITLE
Fix compile errors related to org.protege.editor.owl.model.ChangeListMinimizer...

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege-ontology-client#47]

**Comment by bdionne** [comment]
Not sure this is an issue, you need to build with a [search-api](https://github.com/bdionne/protege/commits/search-api) branch of protege that includes this [patch](https://github.com/bdionne/protege/commit/8bd4242e97c16a67ca8c3542faa56048d547f1ef)

**Comment by rsgoncalves** [comment]
OK. I switched branch and everything compiles now. We were working with 5.0.1-history-search branch.

**Comment by bdionne** [comment]
sorry my bad, I switched to search-api after I replaced use the history manager with the `SessionRecorder`, forgot to notify everyone
