### ISSUE TITLE
Policy Object Details view didn't refresh after user deletion 

### ISSUE THREAD

**Issue by johardi** [protegeproject/protege-ontology-client#53]
The view was still showing the deleted user info. In addition, it triggered the error log dialog to show an error message:

```
ERROR  11:50:47  The specified user (id: joe) is not registered in the access control policy
```

**Comment by rsgoncalves** [comment]
Confirmed. The details view doesnt refresh upon deleting metaproject objects in general.

The error message displayed is from the policy view, which is trying to display assignments for the deleted user. Also a refresh issue.
