### ISSUE TITLE
Protégé 5 freezes on large upload

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege-ontology-client#6]
Upload a large ontology, 35K classes seems to do it, and the revision log diff panel freezes the entire app when you click on the first commit in the commits list.

Perhaps this is just a bug, the server commit history off the main menu seems to load fine, but I'm wondering if this model where the upload results in a single huge commit is going to give us problems

**Comment by rsgoncalves** [comment]
I identified the problem. Worst-case scenario it may involve burdening the server slightly more, but I trust that the client-side improvements I'm working on may be sufficient.
