### ISSUE TITLE
The revision diff tab doesn't handle session timeouts

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege-ontology-client#64]
When a user tries to commit rejections, and the session has timed out, an exception is thrown. It should probably prompt the user to login again and then proceed with the commit, similar to how the `server/commit` menu item works

**Comment by rsgoncalves** [comment]
Could you please paste the exception here?

**Comment by bdionne** [comment]
Just set the server timeout to 60s, connect and wait 60s before doing a commit from the revision tab

![screen shot 2016-09-01 at 5 57 34 am](https://cloud.githubusercontent.com/assets/31741/18187447/85f96e6a-7077-11e6-8edc-30590cb6a58e.png)
