### ISSUE TITLE
Metaproject change breaks the integration tests

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege-ontology-client#70]
The `CRUD` test fails when deleting a user, as the metaproject now expects the [client](https://github.com/bdionne/protege-client/commit/9bac1a0f5fdf) to remove the policy.

**Comment by johardi** [comment]
Fix via https://github.com/protegeproject/protege-client/commit/f0502a34c34ada4bdd8c72740703e2cb9e37d00e
