### ISSUE TITLE
update

### ISSUE THREAD

**Issue by upperli** [protegeproject/protege-ontology-client#71]
When I press the update button, sometimes protege will die! I have to restart protege

**Comment by upperli** [comment]
I use the rmi client,

**Comment by johardi** [comment]
Hi @upperli,
at the moment this project is under a heavy development and it is unstable. The source code in the `master` branch is obsolete and we're about to replace it with the HTTP implementation. We're trying to push a release in the future, but we don't have an exact timeline yet.
